site_name: go-tech-tues
theme:
  name: material
  features:
    - content.code.annotate  
repo_url: https://github.com/tredfield/go-tech-tues
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
